# Generated by Django 3.2.12 on 2022-09-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
    ]
