# Generated by Django 3.2.12 on 2022-09-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0002_auto_20220913_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
