# Generated by Django 3.2.12 on 2022-09-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0003_article_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
