# Generated by Django 3.2.12 on 2022-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0006_alter_article_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(max_length=250),
        ),
    ]
