# Generated by Django 3.2.12 on 2022-09-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0008_auto_20220927_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
