# Generated by Django 3.2.12 on 2022-10-05 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0009_auto_20220927_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(max_length=300),
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_writer', models.TextField(max_length=250)),
                ('commented_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('article_commented', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_comment', to='newscraper.article')),
            ],
        ),
    ]
