# Generated by Django 3.2.12 on 2022-10-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0010_auto_20221005_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='text',
            field=models.CharField(default='What a lame article!', max_length=10000),
        ),
    ]
