# Generated by Django 3.2.12 on 2022-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0015_auto_20221006_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('count', models.IntegerField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
