# Generated by Django 3.2.12 on 2022-10-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0016_wordcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcount',
            name='count',
            field=models.IntegerField(),
        ),
    ]
