# Generated by Django 3.2.12 on 2022-10-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0017_alter_wordcount_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcount',
            name='word',
            field=models.CharField(max_length=50),
        ),
    ]
