# Generated by Django 3.2.12 on 2022-10-12 11:24

from django.db import migrations, models
import django.db.models.deletion
import newscraper.models


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0019_auto_20221010_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='article_commented',
            field=models.ForeignKey(default=newscraper.models.get_default_article, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_comment', to='newscraper.article'),
        ),
    ]
