# Generated by Django 3.2.12 on 2022-10-12 11:53

from django.db import migrations, models
import django.db.models.deletion
import newscraper.models


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0020_alter_articlecomment_article_commented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlereaction',
            name='article',
            field=models.ForeignKey(default=newscraper.models.get_default_article, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_reacted', to='newscraper.article'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='article',
            field=models.ForeignKey(default=newscraper.models.get_default_article, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_comment_reaction', to='newscraper.article'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(default=newscraper.models.get_default_comment, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_reacted', to='newscraper.articlecomment'),
        ),
    ]
