# Generated by Django 3.2.12 on 2022-10-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscraper', '0022_keyword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.AddField(
            model_name='wordcount',
            name='is_keyword',
            field=models.BooleanField(default=False),
        ),
    ]
